<a href="https://colab.research.google.com/github/DCDPUAEM/DCDP_2022/blob/main/01%20Programaci%C3%B3n%20en%20Python/notebooks/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

Numpy es un paquete que provee capacidades de cómputo cientifico para Python. Los componentes principales de Numpy son:

* Un objeto para representar arreglos N-dimensionales.
* Funcionalidades de _broadcasting_.
* Herramientas para integrar código C/C++ y Fortran.
* Funciones de algebra lineal, transformadas de Fourier y creación de números aleatorios.


Puedes importar Numpy en tus programas de Python de la siguiente manera:

In [120]:
#el alias comun de numpy es np
import numpy as np

A diferencia de los objetos de Python para almacenar secuencias, Numpy utiliza _vectorización_ (está optimizado para ser eficiente y utilizar la arquitectura de los procesadores modernos). Además el código generado usando Numpy es más limpio, ya que se aproxima a utilizar un lenguaje matemático.

# Numpy arrays (Arreglos)

Los Numpy ndarrays o arreglos múlti-dimensionales son el principal objeto para el cómputo cientifico. Un arreglo multi-dimensional es una "tabla" (normalmente de números) que almacena datos del mismo tipo. Los arreglos de Numpy están indexados por tuplas de enteros no negativos. Las dimensiones de los arreglos son conocidos como _axes_ o axis.


---

Para ejemplificar, utilicemos el siguiente arreglo que representa un punto en un espacio 3D $(x, y, z)$:

[1, 2, 1] 

Este arreglo tiene un solo axis y una longitud de 3, ya que contiene tres elementos.


---


Un segundo ejemplo, usemos el siguiente arreglo que representa a una matriz:


[[1, 0, 0],

[0, 1, 2]]


Este es un arreglo con dos axis, el primer axis con logitud 2 y el segundo axis con longitud 3 (dos filas y tres columnas).


In [2]:
#creando un arreglo con una funcion de numpy
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Atributos principales de arreglos

* [```ndarray.shape```](https://numpy.org/doc/1.17/reference/generated/numpy.ndarray.shape.html#numpy.ndarray.shape) La longitud de las dimensiones del arreglo representadas como una tupla de enteros. Cada elemento de la tupla es el entero que representa el tamaño del arreglo en el respectivo axis. Para una matriz con $n$ filas y $m$ columnas, el atributo shape retornará la tupla $(n, m)$, dos dimensiones con $n$ y $m$ elementos respectivamente.

* [```ndarray.ndim```](https://numpy.org/doc/1.17/reference/generated/numpy.ndarray.ndim.html#numpy.ndarray.ndim) El número de axis (o dimensiones) en el arreglo.

* [```ndarray.size```](https://numpy.org/doc/1.17/reference/generated/numpy.ndarray.size.html#numpy.ndarray.size)
    El número total de elementos en el arreglo.
    
* [```ndarray.dtype```](https://numpy.org/doc/1.17/reference/generated/numpy.ndarray.dtype.html#numpy.ndarray.dtype)
    Un objeto que representa el tipo de datos usado en el arreglo.
    
* [```ndarray.itemsize```](https://numpy.org/doc/1.17/reference/generated/numpy.ndarray.itemsize.html#numpy.ndarray.itemsize) El número de bytes que utiliza cada elemento en el arreglo.

In [8]:
#creando un arreglo con una funcion de numpy y cambiando su "forma"
a = np.arange(15).reshape(5, 3, 1)
print(a)

print(a.ndim)

[[[ 0]
  [ 1]
  [ 2]]

 [[ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]]]
3


In [4]:
#creando un arreglo con una funcion de numpy y cambiando su "forma"
a = np.arange(15).reshape(3, 5)

#Esto crea una matriz de 3 filas y 5 columnas
print("ndarray a:")
print(a)

#El tipo de dato de a es un arreglo de numpy
print("type(a)", type(a))

#tupla de la longitud de las dimensiones
print("a.shape", a.shape)

#numero de dimensiones en el arreglo
print("a.ndim", a.ndim)

#numero de elementos en el arreglo
print("a.size", a.size)

#tipo de dato de los elementos del arreglo
print("a.dtype", a.dtype)

#numero de bytes del tipo de dato del arreglo
print("a.itemsize", a.itemsize)

ndarray a:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
type(a) <class 'numpy.ndarray'>
a.shape (3, 5)
a.ndim 2
a.size 15
a.dtype int32
a.itemsize 4


## Creación de arreglos desde estructuras de Python

Las estructura de Python (ej, listas y tuplas) que contienen elementos numéricos estructurados como un arreglo pueden ser transformadas a arreglos de Numpy mediante la función ```array()```.

In [9]:
#una lista tradicional de python
numbers_list = [1, 2, 3, 4]
print(numbers_list)
print(type(numbers_list))

#Transformando la lista a un array de numpy
x = np.array(numbers_list)
print(x)
print(type(x))

[1, 2, 3, 4]
<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
#una tupla tradicional de python
numbers_tuple = (1, 2, 3, 4)
print(numbers_tuple)
print(type(numbers_tuple))

#Transformando la tupla a un array de numpy
x = np.array(numbers_tuple)
print(x)
print(type(x))

(1, 2, 3, 4)
<class 'tuple'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [11]:
#una lista de listas de python
numbers_list_list = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(numbers_list_list)
print(type(numbers_list_list))

#Transformando la lista a un array de numpy
x = np.array(numbers_list_list)
print(x)
print(type(x))

[[1, 2, 3, 4], [5, 6, 7, 8]]
<class 'list'>
[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


## Creación de arreglos con funciones de Numpy

Numpy provee algunas funciones para crear arreglos comunmente utilizados:

* [```empty(shape)```](https://numpy.org/doc/1.17/reference/generated/numpy.empty.html#numpy.empty) Retorna un arreglo vacio, (sin elementos) con el shape (tupla de enteros) recibido.

* [```empty_like(a)```](https://numpy.org/doc/1.17/reference/generated/numpy.empty_like.html#numpy.empty_like) Retorna un arreglo sin elementos inicializados con el mismo shape y type del arreglo recibido.

* [```eye(N)```](https://numpy.org/doc/1.17/reference/generated/numpy.eye.html#numpy.eye) Retorna un arreglo 2D con unos en la diagonal y ceros en las demás entradas (identidad).

* [```identity(n[, dtype])```](https://numpy.org/doc/1.17/reference/generated/numpy.identity.html#numpy.identity) Retorna el arreglo identidad.

* [```ones(shape)```](https://numpy.org/doc/1.17/reference/generated/numpy.ones.html#numpy.ones) Retorna un arreglo con sus elementos inicializados con unos.

* [```ones_like(a)```](https://numpy.org/doc/1.17/reference/generated/numpy.ones_like.html#numpy.ones_like) Retorna un arreglo con sus elementos inicializados con unos con el mismo shape y type del arreglo recibido.

* [```zeros(shape)```](https://numpy.org/doc/1.17/reference/generated/numpy.zeros.html#numpy.zeros) Retorna un arreglo con sus elementos inicializados con ceros.

* [```zeros_like(a[, dtype, order, subok, shape])```](https://numpy.org/doc/1.17/reference/generated/numpy.zeros_like.html#numpy.zeros_like) Retorna un arreglo con sus elementos inicializados con ceros con el mismo shape y type del arreglo recibido.

* [```full(shape, fill_value)```](https://numpy.org/doc/1.17/reference/generated/numpy.full.html#numpy.full) Retorna un arreglo con todos sus elementos inicializados con el valor ```fill_value```.

* [```full_like(a, fill_value)```](https://numpy.org/doc/1.17/reference/generated/numpy.full_like.html#numpy.full_like) Retorna un arreglo con todos sus elementos inicializados con el valor ```fill_value``` y el mismo shape del arreglo recibido.

_shape siempre es una tupla que indica el número de elemento en cada dimensión._

### empty

In [17]:
#empty regresa un arreglo sin inicializar
e = np.empty((3, 3))

#el arreglo puede contener valores "basura"
print(e)

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 6.897e-321]
 [0.000e+000 0.000e+000 0.000e+000]]


### empty_like

In [18]:
#un arreglo numpy
a = np.array([[1,2,3],[4,5,6]])

#empty like copia el shape y type de a
e_l = np.empty_like(a)
print(e_l)

[[1 2 3]
 [4 5 6]]


### eye

Una [matriz identidad](https://es.wikipedia.org/wiki/Matriz_identidad) es una matriz que cumple la propiedad de ser el elemento neutro del producto de matrices. Esto quiere decir que el producto de cualquier matriz por la matriz identidad (donde dicho producto esté definido) no tiene ningún efecto. Una matriz identidad contiene unos en su diagonal.

In [23]:
#matriz identidad 3x3
idtt = np.eye(3)

print(idtt)
print(type(idtt))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
<class 'numpy.ndarray'>


### identity

La función ```identity``` es similar a la función ```eye``` para generar una matriz identidad.





In [24]:
#matriz identidad 3x3
idtt = np.identity(3)
print(idtt)
print(type(idtt))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
<class 'numpy.ndarray'>


### ones

In [25]:
#arreglo con unos
o = np.ones((3, 3))

print(o)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### ones_like

In [27]:
#un arreglo numpy
a = np.array([[1,2,3],[4,5,6]])

#arreglo con unos
o_l = np.ones_like(a)

print(o_l)

[[1 1 1]
 [1 1 1]]


### zeros

In [28]:
#arreglo con ceros
z = np.zeros((3, 3))

print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### zeros_like

In [29]:
#un arreglo numpy desde una lista de listas
a = np.array([[1,2,3],[4,5,6]])

#arreglo con ceros
z_l = np.zeros_like(a)
print(z_l)

[[0 0 0]
 [0 0 0]]


### full

In [34]:
#un arreglo 3x3 inicializado con 5 en todos sus elementos
f = np.full((3, 3), 5)

print(f)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


### full_like

In [35]:
#un arreglo numpy
a = np.array([[1,2,3],[4,5,6]])

#un arreglo con la misma dimension que a pero inicializado con valores 5
f_l = np.full_like(a, 5)

print(f_l)

[[5 5 5]
 [5 5 5]]


### arange

**Rangos numéricos**

Tambien puedes crear arreglos con rangos numéricos usando las siguientes funciones:

* [```arange([start,] stop)```](https://numpy.org/doc/1.17/reference/generated/numpy.arange.html#numpy.arange) Retorna un arreglo con una sucesión artimética (cada elemento está separado por la misma distancia), similar a la función range de Python.

* [```linspace(start, stop, num)```](https://numpy.org/doc/1.17/reference/generated/numpy.linspace.html#numpy.linspace) Retorna un arreglo con una progresión artimética en el intervalo recibido.

* [```logspace(start, stop, num)```](https://numpy.org/doc/1.17/reference/generated/numpy.logspace.html#numpy.logspace) Retorna números separados igualmente en una escala logaritmica.

* [```geomspace(start, stop, num)```](https://numpy.org/doc/1.17/reference/generated/numpy.geomspace.html#numpy.geomspace) Retorna números en una progresión geométrica.

In [37]:
#arange 0-9
ar = np.arange(5,10)

print(ar)

[5 6 7 8 9]


### linspace

La función linspace retorna una progresión aritmetica de acuerdo a los parémtros de entrada. Una [progresión aritmética](https://es.wikipedia.org/wiki/Progresi%C3%B3n_aritm%C3%A9tica) es una sucesión de números tales que la diferencia de cualquier par de términos sucesivos de la secuencia es constante. En una progresión aritmética, si se toman dos términos consecutivos de cualquiera de esta, la diferencia entre ambos es una constante, denominada diferencia. Esto se puede expresar como una relación de recurrencia de la siguiente manera: 

$d = a_{n+1}-a{n}$

Conociendo el primer término $a_1$ y la diferencia $d$, podemos utilizar la siguiente fórmula para calcular el enésimo término de la progresión:

$a_n = a_1 + (n-1)d$





Una visualización de los arreglos generados por la función linspace:

![linspace](https://docs.scipy.org/doc/numpy/_images/numpy-linspace-1.png)

In [110]:
#Una progresion aritmetica, 6 muestras espacios iguales
ls = np.linspace(1., 7, num = 6)

print(ls)

[1.  2.2 3.4 4.6 5.8 7. ]


### logspace

La función logspace retorna un arreglo con números separados por espacios iguales en una escala logarítmica.

El primer número en el arreglo está definido por el parámetro ```start```:

start    : [float] start(base ** start) of interval range.

El último número en el arreglo está definido por el parámetro ```end```:

stop     : [float] end(base ** stop) of interval range

Logspace es igual al siguiente código:

```
y = np.linspace(start, stop, num=num, endpoint=endpoint)
power(base, y).astype(dtype)
```

Una visualización de los arreglos generados por la función:

![logspace](https://docs.scipy.org/doc/numpy/_images/numpy-logspace-1.png)

In [109]:
#logarithmic space, 5 muestras
log_s = np.logspace(0.1, 1, num = 5)

print(log_s)

[ 1.25892541  2.11348904  3.54813389  5.95662144 10.        ]


### geomspace
Una [progresión geométrica](https://es.wikipedia.org/wiki/Progresi%C3%B3n_geom%C3%A9trica) es una sucesión de números reales en la que el elemento siguiente se obtiene multiplicando el elemento anterior por una constante denominada razón o factor de la progresión. Se puede obtener el valor de un elemento arbitrario de la secuencia mediante la expresión del término general, siendo $a_{n}$, el término en cuestión, $a_{1}$ el primer término y  $r$, la razón:

$a_n = a_1 * r^{n-1}$



In [108]:
#progresion geometrica, 4 muestras
geo_s = np.geomspace(1, 1000, num = 4) #(inicia 
#la sucesion geometrica **a1**, términa la sucesion , numero de elementos de la sucesion )

print(geo_s)
razon = geo_s[2] / geo_s[1]
print(razon)

[   1.   10.  100. 1000.]
10.0


## Creación arreglos desde archivos en disco

Normalmente los arreglos de gran tamaño son creados desde archivos en disco. Numpy provee estas funciones para crear arreglos desde archivos:

* [```loadtxt(fname[, dtype, comments, delimiter, …])```](https://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html#numpy.loadtxt) Carga datos desde un archivo de texto.
* [```genfromtxt(fname[, dtype, comments, …])```](https://docs.scipy.org/doc/numpy/reference/generated/numpy.genfromtxt.html#numpy.genfromtxt) Carga datos desde un archivo de texto, permite el manejo de datos faltantes.

Un archivo pre-cargado en colab.

In [118]:
!head -n 3 sample_data/mnist_test.csv

"head" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.


In [119]:
#Cargando el archivo a un arreglo de numpy usando coma como delimitador
dataset = np.loadtxt("/content/sample_data/mnist_test.csv", delimiter=",")
print(dataset)

OSError: /content/sample_data/mnist_test.csv not found.

## Creación arreglos aleatorios

El módulo random de Numpy provee capacidades para generar arreglos de números pseudo-aleatorios con las siguientes funciones:

**Aleatorios simples**

* [integers](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html#numpy.random.Generator.integers)
* [random](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html#numpy.random.Generator.random)
* [choice](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.choice.html#numpy.random.Generator.choice)


**Permutaciones**

* [shuffle](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.shuffle.html#numpy.random.Generator.shuffle)
* [permutation](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.permutation.html#numpy.random.Generator.permutation)


**[Aleatorios de distribuciones](https://numpy.org/doc/stable/reference/random/generator.html#distributions)**

* [normal](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.normal.html#numpy.random.Generator.normal)
* [uniform](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.uniform.html#numpy.random.Generator.uniform)
* [binomial](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.binomial.html#numpy.random.Generator.binomial)


### integers

In [ ]:
#generar 10 numeros aleatorios de un rango de 0 a 100
r_ints = np.random.randint(0, 100, size = 10)

print(r_ints)

### random

In [ ]:
#Generar  un arreglo con 10 numeros aleatorios flotantes de 0 a 1
r_floats = np.random.random(size=10)

print(r_floats)

### choice

In [ ]:
#un arreglo del 0 a 99
a = np.arange(100)

#10 elementos aleatorios de a
r_choice = np.random.choice(a, size = 10)
print(r_choice)

### shuffle

In [ ]:
#un arreglo del 0 a 99
a = np.arange(100)
print(a)

#mezclar los elementos de a, afecta al arreglo directamente
np.random.shuffle(a)
print(a)

### permutation

In [ ]:
#un arreglo del 0 a 99
a = np.arange(100)
print(a)

#mezclar los elementos de una copia de a, regresa un nuevo arreglo
r_permu = np.random.permutation(a)
print(r_permu)
print(a)

### normal

Genera un arreglo con numeros aleatorios de una distribución normal parametizada por su media (loc) y desviación estándar (scale), con una función de densidad:

$$
N(x; \mu, \sigma^2) = \dfrac{1}{\sqrt{2\pi \sigma}}\exp({-\dfrac{(x-\mu)^2}{2\sigma^2}})
$$

In [ ]:
#generar 10 numeros aleatorios de una distribucion normal con media 0 y desviacion estandar 1
r_normal = np.random.normal(loc = 0, scale = 1, size=10)

print(r_normal)

### uniform
Genera un arreglo con numeros aleatorios de una distribución uniforme en un rango $A$ (low), $B$ (high), con una función de densidad:

$$
U(x; A, B) = \begin{cases}
\dfrac{1}{B-A} & A \leq x \leq B\\
0 & \text{cualquier otro caso.}\\
\end{cases}
$$

In [ ]:
#generar 10 numeros aleatorios en el rango 0 10 con la misma probabilidad de ser elegidos (uniforme)
r_uniform = np.random.uniform(low = 0, high = 10, size=10)

print(r_uniform)

### binomial

Genera un arreglo con numeros aleatorios de una distribución binomial, con una función de masa de probabilidad:

$$
B(x; n, p) = \binom{n}{x}p^x (1-p)^{n-x}
$$

$n$ - número de experimentos.


$p$ - probabilidad de experimento exitoso.

In [ ]:
#generar 10 numeros aleatorios con distribucion binomial
r_binomial = np.random.binomial(n = 10, p = 0.5, size=10)

print(r_binomial)

# Indexación de arreglos Numpy

De manera similar a Python, puedes utilizar inidices para seleccionar elementos en los arreglos de numpy, por ejemplo puedes usar la siguiente notación para arreglos 1D:



```
a[n]
```

O las siguientes para arreglos con 2 o más dimensiones:



```
a[n1, n2, ..., nn]
```

O


```
a[n1][n2]...[nn]
```


In [ ]:
#1d
a = np.arange(10)

print(a[2])

In [ ]:
#2d
A = np.arange(9).reshape((3, 3))
print("A:")
print(A)

#dos tipos de indexacion
print("2,1:", A[2, 1])
print("0,2:", A[0][2])

## Slicing

Al igual que objetos de Python, los arreglos en Numpy pueden utilizar slicing para obtener _vistas_ de los elmentos en los arreglos.

In [ ]:
#en 1D
a = np.arange(10)

print(a[5:])

In [ ]:
#en 2D
A = np.arange(9).reshape((3, 3))
print("A:")
print(A)

#slice de todos los elementos de la columna en el indice 2
print("A[:, 2]:", A[:,2])

## Indexación Booleana

También puedes utilizar expresiones booleanas para seleccionar a elementos de arreglos en numpy.

In [ ]:
a = np.arange(10)
print(a)

print(a[a>6])

# Constantes

Numpy contiene como atributos a algunas variables matemáticas comunmente utilizadas:

* np.pi
* np.e
* np.Infinity
* np.NINF
* np.NaN

In [ ]:
print(np.pi)
print(np.e)

# Manipulación de arreglos

## Reshape

El método y función ```reshape()``` permite cambiar la "forma" de arreglos. Por ejemplo, para convertir un arreglo 1D a uno 2D. Reshape crea nuevos axis donde apareceran en orden original los elementos del arreglo.

In [ ]:
#un arreglo 1d con nueve elementos
a = np.arange(9)
print(a)
print(a.shape)

#cambiar la forma del arreglo a uno con dos dimentiones (una matriz 3x3) con reshape
A = np.copy(a.reshape((3, 3)))
print(A)
print(A.shape)

## Ravel

El método ravel te permite transformar arreglos con más de una dimensión a arreglos "planos" con una sola dimensión.

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print(A.shape)

a = np.copy(A.ravel())
print(a)
print(a.shape)

## Unión de arreglos

Numpy provee las siguientes funciones para concatenar arreglos de diferentes maneras:

* [```concatenate((a1, a2, ...), [axis]```)](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy.concatenate) Concatenar los elementos de los arreglos usando el axis determinado.

* [```vstack((a1, a2))```](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html#numpy.vstack) Concatenar verticalmente (por filas) los elementos de los arreglos.
  
* [```hstack((a1, a2))```](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html#numpy.hstack) Concatenar horizontalmente (por columnas) los elementos de los arreglos.

In [ ]:
a = np.arange(5)
print(a)
b = np.arange(6, 10)
print(b)

ab = np.concatenate((a, b), axis = 0)
print(ab)

In [ ]:
A = np.arange(9).reshape(3, 3)
B = np.arange(9, 18).reshape(3, 3)
print(A)
print(A.shape)
print(B)
print(B.shape)

print()

AB = np.vstack((A, B))
print(AB)
print(AB.shape)

In [ ]:
A = np.arange(9).reshape(3, 3)
ones = np.ones(3).reshape(3, 1)
print(A)
print(A.shape)
print(ones)
print(ones.shape)

print()

A = np.hstack((ones, A))
print(A)
print(A.shape)

## Splits

* [```split()```](https://numpy.org/doc/stable/reference/generated/numpy.split.html#numpy.split) Divide un arreglo en múltiples arreglos.

* [```vsplit()```](https://numpy.org/doc/stable/reference/generated/numpy.vsplit.html#numpy.vsplit) Divide un arreglo por filas.

* [```hsplit()```](https://numpy.org/doc/stable/reference/generated/numpy.hsplit.html#numpy.hsplit) Divide un arreglo por columnas.

In [ ]:
a = np.arange(10)

#divide en 5 partes iguales
print(np.split(a, 5))

#divide usando indices
print(np.split(a, [3, 6]))

In [ ]:
A = np.arange(9).reshape(3, 3)
print("A:", A)

print()

#dividir por filas a dos arreglos usando un indice
A1, A2 = np.vsplit(A, [1])
print(A1)
print()
print(A2)

In [ ]:
A = np.arange(9).reshape(3, 3)
print("A:", A)

print()

#dividir por columnas a dos arreglos usando un indice
A1, A2 = np.hsplit(A, [1])
print(A1)
print()
print(A2)

# Salida a archivos

Numpy provee algunas funciones para la persistencia en disco de los arreglos de numpy, en particular, las siguientes funciones están disponibles:

* [```save(file, arr)```](https://numpy.org/doc/stable/reference/generated/numpy.save.html#numpy.save) Guarda el arreglo de Numpy en disco usando el formato binario de Numpy _.npy_.

* [```savetxt(file, arr)```](https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html#numpy.savetxt) Guarda el arreglo de Numpy en disco usando un formato de texto plano.

In [ ]:
a = np.arange(20).reshape(5, 4)

#guardar el arreglo en formato binario
np.save("bina", a)

#guardar en formato de texto
np.savetxt("texta", a)

Usemos la línea de comando de linux para ver los archivos almacenados.

In [ ]:
!ls

Podemos ver directamente el archivo guardado en formato de texto.

In [ ]:
!cat texta

# Funciones

## Aritméticas

Numpy permite aplicar [operadores aritméticos](https://numpy.org/doc/stable/reference/routines.math.html#arithmetic-operations) a los arreglos numéricos. Puedes utilizar los siguientes operadores en arreglos múlti-dimensionales:

* [```add(x1, x2)```](https://numpy.org/doc/stable/reference/generated/numpy.add.html#numpy.add) y ```+``` suma los elementos de dos arreglos.
  
* [```subtract(x1, x2)```](https://numpy.org/doc/stable/reference/generated/numpy.subtract.html#numpy.subtract) y ```-```  resta los elementos de dos arreglos.
  
* [```divide(x1, x2)```](https://numpy.org/doc/stable/reference/generated/numpy.subtract.html#numpy.divide) y ```/``` divide los elementos de dos arreglos.
  

* [```multiply(x1, x2)```](https://numpy.org/doc/stable/reference/generated/numpy.multiply.html#numpy.multiply) y ```*``` multiplica los elementos de dos arreglos.
  
* [```power(x1, x2)```](https://numpy.org/doc/stable/reference/generated/numpy.power.html#numpy.power) eleva a la potencia del segundo arreglo los elementos del primero.
  
* [```mod(x1, x2)```](https://numpy.org/doc/stable/reference/generated/numpy.mod.html#numpy.mod) calcula el módulo de un arreglo usando el segundo.


*Nota: Los operadores son aplicados elemento por elemento en los arreglos Numpy, éstos pueden tener múltiples dimensiones. En otra sección verás **broadcasting** para aplicar operaciones en arreglos con dimensiones diferentes.*

### add() y $+$

In [ ]:
#puedes sumar dos arreglos elemento por elemento usando la funcion add o +
a = np.arange(5)
print("a", a)

b = np.arange(6, 11)
print("b", b)

print("add(a, b)")
print(np.add(a, b))

#usando + directamente
print("a + b")
print(a + b)

In [ ]:
#las funciones tambien funcionan en arrelgos multidimensionales
a = np.ones((3, 3))
print("a", a)

b = np.full((3, 3), 6)
print("b", b)

print("add(a, b)")
print(np.add(a, b))

#usando + directamente
print("a + b")
print(a + b)

### subtract() y $-$

In [ ]:
#puedes restar dos arreglos elemento por elemento usando la funcion subtract o -
a = np.arange(5)
print("a", a)

b = np.ones(5)
print("b", b)

print("subtract(a, b)")
print(np.subtract(a, b))

#usando - directamente
print("a - b")
print(a - b)

### divide() y $/$

In [ ]:
#puedes dividir dos arreglos elemento por elemento usando /
a = np.arange(10)
print("a", a)

b = np.full(10, 2)
print("b", b)


#dividir a / b
print("a / b")
print(a / b)

### multiply y $*$

In [ ]:
#puedes multuplicar dos arreglos elemento por elemento usando *
a = np.arange(10)
print("a", a)

b = np.full(10, 3)
print("b", b)


#dividir a * b
print("a * b")
print(a * b)

### power()

In [ ]:
#puedes elevar los elementos de un arreglo a la potencia de los elementos de otro usando power
a = np.full(10, 2)
print("a", a)

b = np.arange(10)
print("b", b)


#dividir np.power(a, b)
print("np.power(a, b)")
print(np.power(a, b))

### mod()

## Comparación

Puedes utilizar los operadores de comparación en arreglos de Numpy:

* $==$
* $<$
* $<=$
* $>$
* $>=$

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])
print("a:", a)
print("b:", b)

print()

print("a == b", a == b)
print("a > b", a > b)
print("a >= b", a >= b)
print("a < b", a < b)
print("a <= b", a <= b)

In [ ]:
#puedes aplicar la operacion modulo a los elementos de un arreglo con los de otro
a = np.arange(3, 10)
print("a", a)

b = np.full_like(a, 3)
print("b", b)


#dividir np.mod(a, b)
print("np.mod(a, b)")
print(np.mod(a, b))

## Trigonométricas

Numpy provee [funciones trigonométricas](https://numpy.org/doc/stable/reference/routines.math.html#trigonometric-functions) que puedes aplicar a los elementos de los arreglos. Algunas de las más comúnes:


* [```sin(x)```](https://numpy.org/doc/stable/reference/generated/numpy.sin.html#numpy.sin) función seno aplicada elemento por elemento.

* [```cos(x)```](https://numpy.org/doc/stable/reference/generated/numpy.cos.html#numpy.cos) función coseno aplicada elemento por elemento.

* [```tan(x)```](https://numpy.org/doc/stable/reference/generated/numpy.tan.html#numpy.tan) función tangente aplicada elemento por elemento.

### sin()

In [ ]:
a = np.arange(0, 10) * np.pi/2
print("a", a)

print("sin(a)")
print(np.sin(a))

### cos()

In [ ]:
a = np.arange(0, 10) * np.pi
print("a", a)

print("cos(a)")
print(np.cos(a))

### tan()

In [ ]:
a = np.arange(0, 10)
print("a", a)

print("tan(a)")
print(np.tan(a))

## Estadísticas

Algunas de las [funciones estadísticas](https://numpy.org/doc/stable/reference/routines.statistics.html#statistics) que puedes utilizar con arreglos de Numpy:

* [```amin(a, axis=None)```](https://numpy.org/doc/stable/reference/generated/numpy.amin.html#numpy.amin) encuentra el elemento mínimo en un arreglo.
  
* [```amax(a, axis=None)```](https://numpy.org/doc/stable/reference/generated/numpy.amax.html#numpy.amax) encuentra el elemento máximo en un arreglo.
  
* [```mean(a, axis=None)```](https://numpy.org/doc/stable/reference/generated/numpy.mean.html#numpy.mean) calcula la media del arreglo.
  
* [```median(a, axis=None)```](https://numpy.org/doc/stable/reference/generated/numpy.median.html#numpy.median) encuentra la mediana del arreglo.


* [```std(a, axis=None)```](https://numpy.org/doc/stable/reference/generated/numpy.std.html#numpy.std) calcula la desviación estándar del arreglo.

* [```var(a, axis=None)```](https://numpy.org/doc/stable/reference/generated/numpy.var.html#numpy.var) calcula la varianza del arreglo.

La siguiente imágen muestra el sentido de la operación al especificar ```axis```:

![Numpy axes](https://raw.githubusercontent.com/jhermosillo/DIPLOMADO_CDP/main/01%20Programaci%C3%B3n%20en%20Python/images/axes.png)

Puedes especificar el axis en el que quieres calcular la función si tienes arreglos con más de una dimensión. Por defecto, si no se especifica el axis, entonces el cálculo de las funciones estadísticas se hace para todos los elementos del arreglo, como si fuera un arreglo 1D.

### amin()

In [ ]:
a =  np.arange(10)
print(a)

print("np.amin(a)", np.amin(a))

In [ ]:
#funciones especificando axis para una matriz
a =  np.arange(10).reshape(2, 5)
print(a)
print(a.shape)

#axis = 0, calcula el minimo de cada columna
print("np.amin(a, axis = 0)", np.amin(a, axis = 0))

#axis = 1, calcula el minimo de cada fila
print("np.amin(a, axis = 1)", np.amin(a, axis = 1))

#si no especificas axis entonces regresa el elemento minimo de todo el arreglo 2d
print("np.amin(a)", np.amin(a))

### amax()

In [ ]:
a =  np.arange(10)

print(np.amax(a))

### mean()

La media aritmética de un arreglo.

Sin especificar axis:
$$
	np.mean(x) = \dfrac{np.sum(x)}{n}
$$

axis = 0, la media de todas las filas (fila promedio):

$$
	np.mean(X, axis = 0) = \dfrac{np.sum(X[:, j])}{n}
$$

axis = 1, la media de todas las columnas (columna promedio):

$$
	np.mean(X, axis = 1) = \dfrac{np.sum(X[i, :])}{n}
$$

In [ ]:
#sin especificar axis (la media de todo el arreglo)
a =  np.random.normal(0, 1, 100)

print(np.mean(a))

In [ ]:
#2d, axis = 0
A = np.array([[1, 2], [3, 4]])

# fila promedio
print(np.mean(A, axis=0))

In [ ]:
#2d, axis = 1
A = np.array([[1, 2], [3, 4]])

# columna promedio
np.mean(A, axis=1)

### median()

Sin especificar axis, la mediana de todo el arreglo:

$$
	\begin{matrix}
	np.median(x) = x[(n+1)/2] \quad \text{ si $n$ impar}, \qquad & \dfrac{(x[(n+1)/2] + x[n/2])}{2} \quad \text{si $n$ par}
	\end{matrix}
	$$

axis = 0:

$$
np.median(X[:, j])
$$

axis = 1:

$$
np.median(X[i, :])
$$

In [ ]:
a =  np.random.normal(0, 1, 100)

print(np.median(a))

In [ ]:
#2d, axis = 0
A = np.array([[1, 2], [3, 4], [5, 6]])

print(np.median(A, axis=0))

In [ ]:
#2d, axis = 1
A = np.array([[1, 2, 3], [4, 5, 6]])

np.median(A, axis=1)

### std()

Sin especificar axis, la desviación estándar de todo el arreglo:
$$
	np.std(A) = \sqrt{\frac{np.sum(np.pow(x - np.mean(x), 2))}{n}}
$$

axis = 0:

$$
	np.std(X, axis = 0) = \sqrt{\frac{np.sum(np.pow(X[i, :] - np.mean(X[i, :]), 2))}{X.shape[0]}}
$$

axis = 1:

$$
	np.std(X, axis = 1) = \sqrt{\frac{np.sum(np.pow(X[:, j] - np.mean(X[:, j]), 2))}{X.shape[1]}}
$$

In [ ]:
a =  np.random.normal(0, 1, 100)

print(np.std(a))

In [ ]:
#2d, axis = 0
A = np.array([[1, 2], [3, 4]])

print(np.std(A, axis=0))

In [ ]:
#2d, axis = 1
A = np.array([[1, 2], [3, 4]])

np.std(A, axis=1)

### var()

Sin especificar axis, la varianza de todo el arreglo:
$$
	np.var(x) = \frac{np.sum(np.pow(x - np.mean(x), 2))}{n}
$$

axis = 0:

$$
	np.var(X, axis = 0) = \frac{np.sum(np.pow(X[i, :] - np.mean(X[i, :]), 2))}{X.shape[0]}
$$

axis = 1:

$$
	np.var(X, axis = 1) = \frac{np.sum(np.pow(X[:, j] - np.mean(X[:, j]), 2))}{X.shape[1]}
$$

In [ ]:
a =  np.random.normal(0, 1, 100)

print(np.var(a))

In [ ]:
#2d, axis = 0
A = np.array([[1, 2], [3, 4]])

print(np.var(A, axis=0))

In [ ]:
#2d, axis = 1
A = np.array([[1, 2], [3, 4]])

np.var(A, axis=1)

## Álgebra lineal

Algunas de las [funciones de álgebra lineal](https://numpy.org/doc/stable/reference/routines.linalg.html#linear-algebra-numpy-linalg) que puedes utilizar en arreglos de Numpy:

* [```dot(a, b)```](https://numpy.org/doc/stable/reference/generated/numpy.dot.html#numpy.dot) genera el producto punto de dos arreglos, el tipo de operación (multiplicación de matrices o producto punto) depende de la entrada (2D o 1D).
  
* [```vdot(a, b)```](https://numpy.org/doc/stable/reference/generated/numpy.vdot.html#numpy.vdot) genera el producto punto de dos vectores (1D). _vdot() permite computar vectores con números complejos._

* [```matmul(x1, x2) o @```](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html#numpy.matmul) para la multiplicación de matrices (generalmente 2D).

* [```inner(a, b)```](https://numpy.org/doc/stable/reference/generated/numpy.inner.html#numpy.inner) genera el producto interno o producto escalar de dos arreglos.
  
* [```outer(a, b)```](https://numpy.org/doc/stable/reference/generated/numpy.outer.html#numpy.outer) genera el producto externo (tensorial) de dos arreglos.

* [```trace(a)```](https://numpy.org/doc/stable/reference/generated/numpy.trace.html#numpy.trace) genera la traza (suma de los elementos en la diagnonal) del arreglo.

### dot()

Para dos vectores (1D), es el producto punto:
$$u = [u_1, \dots, u_n]$$
$$v = [v_1, \dots, v_n]$$
$$
	np.dot(u, v) = u_1 v_1 + u_2 v_2 + \dots + u_n v_n
$$

In [ ]:
#cuando recibe dos vectores dot() produce el producto punto
a = np.array([2, 3])
b = np.array([3, 4])
print("a:\n", a)
print("b:\n", b)

print("dot(a, b): ", np.dot(a ,b))

Para matrices (2D), el producto de matrices:

$$
	C = np.dot(A, B) \Leftrightarrow C[i,j] = np.sum(a[i,:]*b[:,j])
$$

_Las dimensiones de ambos arreglos deben cumplir los requisitos del producto de matrices, esto es,  el número de columnas en el primero debe ser igual al número de filas en el segundo._

In [ ]:
#cuando recibe dos arreglos 2d dot() produce la multiplicacion de matrices
A = np.array([[2, 0], [0, 2]])
B = np.array([[4, 1], [2, 1]])
print("A:\n", A)
print("B:\n", B)

print("dot(A, B):\n", np.dot(A, B))

### matmul() o @
Para matrices (2D), el producto de matrices:

$$
	C = np.matmul(A, B) = A @ B \Leftrightarrow C[i,j] = np.sum(A[i,:]*B[:,j])
$$

_Las dimensiones de ambos arreglos deben cumplir los requisitos del producto de matrices, esto es,  el número de columnas en el primero debe ser igual al número de filas en el segundo._

In [ ]:
#matmul para el producto de matrices
#Las dimensiones deben cumplir los requisitos del producto de matrices
A = np.array([[2, 0], [0, 2]])
B = np.array([[4, 1], [2, 1]])
print("A:\n", A)
print("B:\n", B)

print("matmul(A, B):\n", np.matmul(A, B))
print("igual a")
print("A @ B:\n", A @ B)

### vdot()

Para la multipliación exclusiva de vectores (1D), producto punto:

$$u = [u_1, \dots, u_n]$$
$$v = [v_1, \dots, v_n]$$
$$
	np.vdot(u, v) = u_1 v_1 + u_2 v_2 + \dots + u_n v_n
$$

In [ ]:
a = np.array([2, 3])
b = np.array([3, 4])
print("a:\n", a)
print("b:\n", b)

print("vdot(a, b): ", np.vdot(a ,b))

### inner()

Producto punto de vectores (1D):

$$u = [u_1, \dots, u_n]$$
$$v = [v_1, \dots, v_n]$$
$$
	np.inner(u, v) = u_1 v_1 + u_2 v_2 + \dots + u_n v_n
$$

In [ ]:
a = np.array([1,2,3])
b = np.array([0,1,0])
print("a:\n", a)
print("b:\n", b)

print("inner(a, b): ", np.inner(a ,b))

### outer()

El producto tensorial de dos vectores (1D), genera una matriz:
$$u = [u_1, \dots, u_n]$$
$$v = [v_1, \dots, v_m]$$
$$
	np.outer(u, v) = \begin{bmatrix}
	u_{1} v_{1} & u_{1} v_{2} & \dots & u_{1} v_{m}  \\
	u_{2} v_{1} & u_{2} v_{2} & \dots & u_{2} v_{m}  \\
  \vdots & \vdots  & \dots & \vdots \\
	u_{n} v_{1} & u_{n} v_{2} & \dots & u_{n} v_{m}  \\
	\end{bmatrix}
	$$

In [ ]:
#el producto tensorial de dos vectores produce una matriz
a = np.array([1,2,3])
b = np.array([1,1,1])
print("a:\n", a)
print("b:\n", b)

print("outer(a, b): ", np.outer(a ,b))

### trace()

Calcula la traza de un arreglo (2D):

$$
	trace(A) = np.sum(A[i,i])
$$

In [ ]:
#para calcular la traza de un arreglo 2d (matriz)
#La traza es la suma de los elementos en la diagonal
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("A:\n", A)

print("trace(A):", np.trace(A))

## Métodos de arreglos

Además de las funciones que se encuentran disponibles en los módulos de Numpy, los [ndarrays tienen disponibles métodos](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray) para calcular diferentes estadísticas (funciones de agregación), entre éstas se encuentran:

* [```sum(axis=None)```](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sum.html#numpy.ndarray.sum) retorna la suma de todos los elementos del arreglo o la suma por axis si es especificado.
  
* [```min(axis=None)```](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.min.html#numpy.ndarray.min) retorna el elemento mínimo del arreglo o de cada axis si especificado.
  
* [```max(axis=None)```](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.max.html#numpy.ndarray.max) retorna el elemento máximo del arreglo o de cada axis si especificado

* [```mean(axis=None)```](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.mean.html#numpy.ndarray.mean) retorna la media del arreglo, puede recibir el axis.

* [```std(axis=None)```](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.std.html#numpy.ndarray.std) retorna la desviación estándar del arreglo, puede recibir el axis.

* [```var(axis=None)```](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.var.html#numpy.ndarray.var) retorna la varianza del arreglo, puede recibir el axis.

### sum(), min() y max()

In [ ]:
#metodos para arreglos 1D
a = np.arange(10)
print("a:", a)

print("sum(a):", a.sum())
print("min(a):", a.min())
print("max(a):", a.max())

In [ ]:
#metodos para arreglos 2d especificando axis
a = np.arange(10).reshape(2, 5)
print("a:", a)


print("axis = 0")
print("a.sum(axis = 0):", a.sum(axis = 0))
print("a.min(axis = 0):", a.min(axis = 0))
print("a.max(axis = 0):", a.max(axis = 0))

print("axis = 1")
print("a.sum(axis = 1):", a.sum(axis = 1))
print("a.min(axis = 1):", a.min(axis = 1))
print("a.max(axis = 1):", a.max(axis = 1))

### mean(), std() y var()

In [ ]:
a = np.random.normal(0, 1, 100)
#1d
print(a.shape)

print("a.mean():", a.mean())
print("a.std():", a.std())
print("a.var():", a.var())

print()

B = np.vstack((np.random.normal(0, 1, 50), np.random.normal(10, 5, 50)))
#2d
print(B.shape)

print("axis = 1")
print("B.mean(axis = 1):", B.mean(axis = 1))
print("B.std():", B.std(axis = 1))
print("B.var():", B.var(axis = 1))

## Otras funciones matemáticas

Otras [funciones importantes que están disponibles en Numpy](https://numpy.org/doc/stable/reference/routines.math.html):

* [```exp(x)```](https://numpy.org/doc/stable/reference/generated/numpy.exp.html#numpy.exp) calcula la función $e^x$ para todos los elementos del arreglo.

* [```log(x)```](https://numpy.org/doc/stable/reference/generated/numpy.log.html#numpy.log) calcula el logaritmo natural de todos los elementos del arreglo.
 
* [```sqrt(x)```](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html#numpy.sqrt) calcula la raíz cuadrada de los elementos del arreglo.

In [ ]:
a = np.arange(1, 10)
print("a:", a)

print("exp(a):", np.exp(a))
print("log(a):", np.log(a))
print("sqrt(a):", np.sqrt(a))

## Ordenamiento

La función [```sort(a)```](https://numpy.org/doc/stable/reference/generated/numpy.sort.html#numpy.sort) de Numpy puede ser utilizada para ordenar los elementos de un arreglo.

In [ ]:
a = np.random.permutation(np.arange(10))
print("a:", a)

#ordernar el arreglo con sort
print("sort(a):", np.sort(a))

## Búsqueda

Algunas funciones útiles para encontrar elementos en arreglos de Numpy:

* [```argmax(a, axis=None)```](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html#numpy.argmax) regresa el o los índices del elemento con el valor máximo.
  
* [```argmin(a, axis=None)```](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html#numpy.argmin) regresa el o los índices del elemento con el valor mínimo.

* [```where(condition, x, y)```](https://numpy.org/doc/stable/reference/generated/numpy.where.html#numpy.where) regresa los elementos de $x$ o $y$ dependiendo de la condición.



In [ ]:
a = np.arange(10)
print(a)

#argmax
print("Indice del elemento maximo:", np.argmax(a))

In [ ]:
a = np.arange(10)
print(a)

#argmin
print("Indice del elemento minimo:", np.argmin(a))

In [ ]:
#where para seleccionar los elementos de un arreglo basado en una condicion
x = np.arange(10)
print("x:", x)

#where
print("x>3:")
print(np.where(x > 3))

In [ ]:
#where para seleccionar los elementos de un arreglo o el otro de acuerdo a una condicion
x = np.arange(10)
print("x:", x)
y = np.zeros_like(x)
print("y:", y)

#where
print("x<5:")
print(np.where(x < 5, x, y))

# Broadcasting

Numpy permite realizar operaciones aritméticas en arreglos de diferentes tamaños mediante broadcasting. El arreglo de menor tamaño es "transmitido" (broadcasted) para que ambos tengan el mismo tamaño y la operación sea válida. 
Broadcasting permite que este tipo de operaciones entre arreglos sean vectorizadas, lo cual optimiza la ejecución y uso de memoria.

El ejemplo más básico de broadcasting es las operaciones escalar con arreglo, por ejemplo:


```
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b
array([ 2.,  4.,  6.])
```

Es equivalente, pero más eficiente que utilizar:

```
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b
array([ 2.,  4.,  6.])
```



In [ ]:
#sumar un escalar a un arreglo usando broadcasting (evita ciclos de python y optimiza el uso de memoria)
a = np.array([1.0, 2.0, 3.0])
b = 4.0

#equivalente a [1.0, 2.0, 3.0] + [4.0, 4.0, 4.0]
print(a+b)

Podemos pensar que el escalar $b$ está siendo estirado a un arreglo con las mismas dimensiones que $a$ durante la operación aritmética. Los elementos del "nuevo" $b$ son simples copias del escalar original. Esta analogía es solo conceptual, ya que NumPy usa el valor original sin realizar copias físicas de éste. Esto permite que las operaciones sean eficientes en el uso de memoria y computacionalmente.

Más ejemplos:

In [ ]:
#broadcasting un arreglo (vector fila) a una matriz
A = np.arange(9).reshape(3, 3)
b = np.array([1, 2, 3])
print("A", A)
print("b", b)

print(b*A)

In [ ]:
#broadcasting un arreglo (vector columna) a una matriz
A = np.arange(9).reshape(3, 3)
b = np.array([1, 2, 3]).reshape(3, 1)
print("A", A)
print("b", b)

print(b*A)

# Más sobre vectorización

La vectorización, es el proceso de convertir un algoritmo que opera en un solo valor a la vez, a un algoritmo que opera en un conjunto de valores a la vez. Los CPUs modernos proveen instrucciones para llevar a cabo operaciones vectorizadas que permiten aplicar una misma instrucción a múltiples datos ([SIMD: Single instruction, multiple data](https://es.wikipedia.org/wiki/SIMD)).


En general utilizar vectorización permite:

- Aprovechar las arquitecturas múlti-núcleo de los CPUs/GPUs.
- Aprovechar la arquitectura optimizada para la vectorización del hardware (SIMD).
- Obtener código más conciso.


In [ ]:
import time

## Primer ejemplo, sumando un escalar a un arreglo grande

In [ ]:
print("Sumando un escalar a todos los elementos de un arreglo")

a = np.random.rand(1000)
b = 4.0

tic = time.time()
a = a + b
toc = time.time()

print("\nResultado:")
print(a[:10], ",...")
print("Tiempo solucion vectorizada: " + str(1000*(toc-tic)) + "ms")

tic = time.time()
for i in range(1000):
  a[i] += b
toc = time.time()

print("\nResultado:")
print(a[:10], ",...")
print("Tiempo en ciclo for: " + str(1000*(toc-tic))+"ms")

### Un ejemplo, multiplicando dos vectores con una gran cantidad de datos.

In [ ]:
print("Producto punto de dos vectores")

a = np.random.rand(1000)
b = np.random.rand(1000)

print("a.shape:")
print(a.shape)
print("b.shape")
print(b.shape)


tic = time.time()
c = np.dot(a,b)
toc = time.time()

print("\nResultado:")
print(c)
print("Tiempo solucion vectorizada: " + str(1000*(toc-tic)) + "ms")

tic = time.time()
c = 0
for i in range(1000):
    c += a[i]*b[i]
toc = time.time()

print("\nResultado:")
print(c)
print("Tiempo en ciclo for: " + str(1000*(toc-tic))+"ms")

## Comparemos código tradicional con ciclos `for` vs vectorización con `np.dot` para la multiplicación de matrices

In [ ]:
A = np.random.rand(100000, 10)
B = np.random.rand(10, 1)

print("Dimensiones de las matrices A, B")
print("A.shape:")
print(A.shape)
print("B.shape")
print(B.shape)

In [ ]:
#Solucion no vectorizada
tic = time.time()
C = [[0 for j in range(B.shape[1])] for i in range(A.shape[0])]
for i in range(A.shape[0]):#numero de filas en A
    for j in range(B.shape[1]):#numero de columnas en B
        for k in range(B.shape[0]):#numero de filas en B == numero de columnas en A
            #fila i en A por columna j en B (vectores)
            C[i][j] += A[i][k] * B[k][j]
toc = time.time()

print("\nResultado:")
for el in C[:3]:
    print(el)
print("...")
for el in C[-3:]:
    print(el)

print("Tiempo en ciclo for: " + str(1000*(toc-tic))+"ms")

In [ ]:
#vectorizado usando numpy
tic = time.time()
C = np.dot(A, B)
toc = time.time()

print("\nResultado:")
print(C)
print("Tiempo solucion vectorizada: " + str(1000*(toc-tic)) + "ms")